include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - always_declare_return_types
    - avoid_print
    - prefer_final_locals
    - use_key_in_widget_constructors
    - annotate_overrides
    - await_only_futures

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    todo: ignore
    missing_required_param: error
    missing_return: error
